#!/usr/bin/env python
import base64
import json
import requests
import pprint
import os
pp = pprint.PrettyPrinter()

checkform = json.loads(base64.b64decode(os.environ['CHECKFORM']))
resp = requests.post(os.environ['LTIURL'], data=checkform)

print(resp.text)

