#!/bin/bash
if [ ! $TRAININGENVIRONMENT ]; then
    printf "\033[32mIt looks like you are running this in Katacoda \nand not from the Datadog Training Environment. \n\nPlease login to https://learn.datadoghq.com for a working environment.\033[0m\n"
    exit
    exit 1;
fi
show_progress()
{
  local -r pid="${1}"
  local -r delay='1'

  while true; do 
    grep -i "complete" status.txt &> /dev/null
    if [[ "$?" -ne 0 ]]; then     
        sleep "${delay}" 
    else
      break
    fi
    
  done
}
TRAININGENVIRONMENT=$(echo $TRAININGENVIRONMENT | tr - " ")
echo "Now preparing training environment for $TRAININGENVIRONMENT."
while [ ! -f "status.txt" ]; do
  sleep 0.3
done
show_progress
if [ ! -f "/root/provisioned" ]; then
  touch /root/provisioned
  printf "\n\nOK, the training environment is installed and ready to go.\n\n"
else
  printf "\n\nWelcome back to the training lab.\n\n"
fi
printf "Provisioning Complete\n\n"