#!/bin/bash
if [ ! $trainingenvironment ]; then
  # if it's an upgrade, then we will use the transition script
    printf "\033[31mIt looks like you are running this in Katacoda rather than from the Datadog Training Environment. Please login to https://learn.datadoghq.com for a working environment.\033[0m\n"
    exit 1;
fi
echo "Now preparing training environment for $trainingenvironment."
show_progress()
{
  local -r pid="${1}"
  local -r delay='0.75'
  local spinstr='\|/-'
  local temp

  while true; do 
    grep -i "done" status.txt &> /dev/null
    if [[ "$?" -ne 0 ]]; then     
      status=`cat status.txt`
      printf "${status}"
      temp="${spinstr#?}"
      printf " [%c]  " "${spinstr}"
      spinstr=${temp}${spinstr%"${temp}"}
      sleep "${delay}"
      printf "\r                                           \r"

    else
      break
    fi
  done

}

show_progress