#!/usr/bin/env python3
import base64
import json
import requests
import pprint
import os
from datetime import datetime
pp = pprint.PrettyPrinter()

if "CHECKFORM" in os.environ:
  if len(os.environ["CHECKFORM"]) > 0:
    checkform = json.loads(base64.b64decode(os.environ['CHECKFORM']).decode('utf-8'))
    resp = requests.post(os.environ['LTIURL'], data=checkform).text
else:
  resp = "GRADEME not configured on this exercise. If you are not at DASH or Summit, first try refreshing your browser. If you get the same message, please let the Training team know on the public Slack or click the blue smile at the bottom left of the screen on the Learning Center to provide feedback"
print(datetime.now().strftime("%d/%m/%Y %H:%M:%S"))
print(resp)
