#!/bin/bash
wget -q --post-data="{\"name\": \"$LABUSER\", \"email\": \"$LABUSER\", \"section\": \"$TRAININGENVIRONMENT\"}" --header='Content-Type:application/json' 'https://ddlabs.netlify.com/.netlify/functions/start'
